version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agenda_db_container
    environment:
      POSTGRES_USER: admin_agenda
      POSTGRES_PASSWORD: senha_secreta_infra
      POSTGRES_DB: agenda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_agenda -d agenda_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - agenda_network

volumes:
  postgres_data:

networks:
  agenda_network:
    driver: bridge